# Generated by Django 4.2.2 on 2023-06-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='detalles',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
