# Generated by Django 4.2.3 on 2023-08-11 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_usuario_idtipousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='idTipoUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.tipo_usuario'),
        ),
    ]
