# Generated by Django 4.2.2 on 2023-06-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_solicitud_detalles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='desde',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='hasta',
            field=models.TextField(max_length=50),
        ),
    ]
