# Generated by Django 4.2.2 on 2023-06-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_alter_solicitud_desde_alter_solicitud_hasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='desde',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='hasta',
            field=models.CharField(max_length=50),
        ),
    ]
