# Generated by Django 4.2.3 on 2023-08-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_alter_usuario_idtipousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='desde',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='hasta',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='coordenadas_desde',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='coordenadas_hasta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='direccion_desde',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='direccion_hasta',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='objetos_a_transportar',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='detalles',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
