# Generated by Django 4.2.3 on 2023-08-03 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_alter_cliente_puntos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='idEstadoCliente',
            field=models.ForeignKey(blank=0, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.estadoscliente'),
        ),
    ]
