# Generated by Django 4.2.2 on 2023-06-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_alter_solicitud_desde_alter_solicitud_hasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('1', 'A presupuestar'), ('2', 'Confirmado'), ('3', 'En camino'), ('4', 'Entregado'), ('5', 'Cobrado')], default=1, max_length=1),
        ),
    ]
