# Generated by Django 4.2.3 on 2023-08-15 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_rename_idestadocliente_cliente_id_estado_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='calificacion',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
