# Generated by Django 4.2.3 on 2023-08-03 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_alter_cliente_idestadocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='idEstadoCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.estadoscliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='puntos',
            field=models.IntegerField(),
        ),
    ]
