# Generated by Django 4.2.2 on 2023-07-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_alter_solicitud_fechatrabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fechaTrabajo',
            field=models.DateTimeField(),
        ),
    ]
