# Generated by Django 4.2.3 on 2023-08-17 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_alter_solicitud_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cliente_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.cliente'),
        ),
    ]
