# Generated by Django 4.2.3 on 2023-08-23 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_empleadoadministrativo_fecha_nac_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='empleadocalle',
            options={'verbose_name_plural': 'Empleados de calle'},
        ),
        migrations.AlterModelOptions(
            name='estadoscliente',
            options={'verbose_name_plural': 'Estados de clientes'},
        ),
        migrations.AlterModelOptions(
            name='estadosempleadocalle',
            options={'verbose_name_plural': 'Estados de empleados de calle'},
        ),
        migrations.AlterModelOptions(
            name='estadossolicitud',
            options={'verbose_name_plural': 'Estados de solicitudes'},
        ),
        migrations.AlterModelOptions(
            name='estadostransporte',
            options={'verbose_name_plural': 'Estados de solicitudes'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'verbose_name_plural': 'Solicitudes'},
        ),
        migrations.AlterModelOptions(
            name='solicitudesempleados',
            options={'verbose_name_plural': 'Solicitudes y Empleados'},
        ),
        migrations.AlterModelOptions(
            name='solicitudestransportes',
            options={'verbose_name_plural': 'Solicitudes y Transportes'},
        ),
        migrations.AlterModelOptions(
            name='tipo_usuario',
            options={'verbose_name_plural': 'Tipos de usuarios'},
        ),
        migrations.AlterModelOptions(
            name='transporte',
            options={'verbose_name_plural': 'Transportes'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'Usuarios'},
        ),
        migrations.DeleteModel(
            name='EmpleadoAdministrativo',
        ),
        migrations.DeleteModel(
            name='EstadosEmpleadoAdmnistrativo',
        ),
    ]
