# Generated by Django 4.2.3 on 2023-08-23 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_alter_cliente_options_alter_empleadocalle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadostransporte',
            options={'verbose_name_plural': 'Estados de transportes'},
        ),
    ]
