# Generated by Django 4.2.3 on 2023-08-23 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0010_alter_estadostransporte_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstadosTransporte',
            new_name='EstadosVehiculo',
        ),
        migrations.RenameModel(
            old_name='SolicitudesTransportes',
            new_name='SolicitudesVehiculos',
        ),
        migrations.RenameModel(
            old_name='Transporte',
            new_name='Vehiculo',
        ),
        migrations.AlterModelOptions(
            name='estadosvehiculo',
            options={'verbose_name_plural': 'Estados de vehiculos'},
        ),
        migrations.AlterModelOptions(
            name='solicitudesvehiculos',
            options={'verbose_name_plural': 'Solicitudes y vehiculos'},
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'verbose_name_plural': 'Vehiculos'},
        ),
        migrations.RenameField(
            model_name='solicitudesvehiculos',
            old_name='id_transporte',
            new_name='id_vehiculo',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='id_estado_transporte',
            new_name='id_estado_vehiculo',
        ),
    ]
