# Generated by Django 4.2.3 on 2023-09-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0013_alter_vehiculo_dominio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_nac',
            field=models.DateField(null=True),
        ),
    ]
