# Generated by Django 4.2.3 on 2023-10-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0014_cliente_fecha_nac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='coordenadas_desde',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='coordenadas_hasta',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='latitud_desde',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='latitud_hasta',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='longitud_desde',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='longitud_hasta',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
