# Generated by Django 4.2.7 on 2023-12-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0019_remove_cliente_fecha_creacion_usuario_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='fecha_ult_service',
            field=models.DateField(null=True),
        ),
    ]
