# Generated by Django 4.2.7 on 2023-12-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0020_vehiculo_fecha_ult_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje_desde_ult_service',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
